### ISSUE TITLE
Problem related to Gender-Neutral Pronouns

### ISSUE THREAD

**Issue by progmatic-99** [ILUGD/Code-of-Conduct#1] opened 2020-05-04 07:59 UTC
I would like to make this clear that i don't have any problem when someone asks to refer to them using a specific pronoun. Now, what is the problem, then?
The problem arises when in a community, it is imposed by other people on a large group of people. I know this rule is decided to make the community a better place for everyone. But, we also have to look into the fact that by telling anyone in a community that you have to use gender-neutral pronouns, you are taking away the individual's ```Right to freedom of Expression and Speech```. Now, again i have no problem in using gender-neutral pronouns, when asked personally by a person. 
By making this a rule in the community, what you are doing is imposing a restriction on a person's individuality and their liberty because a group of people in a community are telling the rest of the group, what words they should be using. Now, that is the issue i have serious qualms with.

Now, this issue was raised by Jordan Peterson.
Links to his arguments:
https://www.youtube.com/watch?v=SiijS_9hPkM
https://www.youtube.com/watch?v=kasiov0ytEc

**Read all the comments that i have put below.**

**Comment by bhanuvrat** [comment] 2020-05-04 08:35
Hi @progmatic-99 Two questions.

Do we, as a community, want create an environment where present and future members want to engage?

If we are not inclusive to begin with, would those who feel marginalized, ever become invested enough in the idea of the community to speak up and raise their demands in the first place?

Could you give an example of a sentence or a snippet of a conversation illustrating the difference caused by the clause you are objecting upon?

**Comment by tm9k1** [comment] 2020-05-04 08:47
I believe no one can force me or anyone to do anything, or utter a specific set of words in any community. There are moderators to moderate any discussions if someone feels offended. Then again I'd like to believe I (or anyone who's not a pathological person) will understand and do the right thing to fix the issue at hand. 😊

**Comment by iayanpahwa** [comment] 2020-05-04 08:55
> I would like to make this clear that i don't have any problem when someone asks to refer to them using a specific pronoun. 

Good to know, this is now an accepted Netiquette to begin with.

> The problem arises when in a community, it is imposed by other people on a large group of people.

By "Other people" I believe you are referring to the organizers and volunteers who are working for the best interest of the community and and 'NO' , things are not imposed, a Code of Conduct by it's foundational definition is what is acceptable and what is not acceptable in a community, events etc and by being participant of that gathering you agree to abide by it and is expected to follow it throughout which are created keeping in mind the inclusivity, safety and interest of other members and participants and especially the under-represented segment of the community.

> we also have to look into the fact that by telling anyone in a community that you have to use gender-neutral pronouns, you are taking away the individual's Right to freedom of Expression and Speech

I beg to differ here, someone may argue using slang is their right to speech but you don't do that in a professional or educational environment in the same way, asking to use Gender Neutral pronouns is not a reservation of Right but rather a safe move to cut unintentional hurt feelings within members towards folks identifying themselves as non Binary or trans . If you are not sure about member’s preferred pronouns or they are not explicit about it, the best way is to use Gender Neutral pronouns (they/them) or politely ask them - **"Hey, what's your preferred pronoun?**" before addressing them. This is way safer than hurting sentiments using wrong pronouns.

> By making this a rule in the community, what you are doing is imposing a restriction on a person's individuality and their liberty because a group of people in a community are telling the rest of the group, what words they should be using. Now, that is the issue i have serious qualms with.

I hope my above points clear this point as well. ILUGD appreciate your PoV and thank you for putting it forward and making it a better place, but as for the current adopted version of the CoC, it is expected of members to communicate with one another using Gender Neutral pronouns and if they are unaware about someone’s preferred pronouns they may ask them first politely before addressing. 

Doing this IMO is not at all violation of right of speech, because using wrong pronouns is not anyone’s ‘right’ at first place, it’s grammatically, ethically and socially incorrect .

Appreciate your feedbacks though  :)

**Comment by grlwholifts** [comment] 2020-05-04 09:35
> If you are not sure about a members preferred pronouns or they are not explicit about it, the best way is to use Gender Neutral pronouns (they/them) or politely ask them - **"Hey, what's your preferred pronouns**" before addressing them. This is way safer than hurting sentiments using wrong pronouns.

Continuing on comments by @iayanpahwa, I would like to propose some changes to the existing CoC :
- It is suggested for all participants to add the choice of their pronoun in their `username`/`bio` hence allowing them freedom to choose their self-identity.
- For new joinees/inactive participants/any other reason, they can be referred to as `they`
- For hints at the choice of pronouns, please have a look [here](https://uwm.edu/lgbtrc/support/gender-pronouns/):

![photo_2020-05-04 14 54 49](https://user-images.githubusercontent.com/30324532/80952457-52a29480-8e17-11ea-92b8-0284f01fced9.jpeg) 

Do note that all these practices have been taken up from open source communities/promoters like Fedora/Outreachy etc which have pretty strict community abidance rules. IMHO, this argument now satisfies all the concerns and hence be closed.
This issue will however, be addressed in the volunteer meeting for better implementation and discussion.

**Comment by progmatic-99** [comment] 2020-05-04 13:21
@iayanpahwa  I agree that the CoC is made for maintaining harmony in the community. But, by telling members to use Gender Specific Pronouns, you are telling them what they must speak, thus, in a way you are curtailing their free speech. Instead of telling what we can't say, you are telling the members what we must say.

I totally agree with you that certain environments require us to behave in a certain way.
**Again, what i am against is the community at large telling an individual that they ```must``` speak a certain way.** Also, any person in their right sense of mind will understand their surroundings and act accordingly.
I agree with you that we can ask an individual their preferred pronoun, then why do we need it as an explicit rule in CoC.
What this signifies is a form of far-left ideology. Though your intentions are of goodwill but the consequences might not be the same.
Also most of these pronouns are made by radical left ideologues. So, not using these pronouns is not grammatically incorrect. Whereas, on an ethical moral ground, it may differ from person to person.
Also, socially, how can you, based on your prejudices, decide for a larger group of people, what is socially acceptable or not?
Thanks for your viewpoints!!
At last, we both want the same thing but the path is different.

**Comment by progmatic-99** [comment] 2020-05-04 13:30
> Hi @progmatic-99 Two questions.
> 
> Do we, as a community, want create an environment where present and future members want to engage?
Yes, i agree with you that we, as a community, should be inclusive to all. But, i am not saying that gender neutral pronouns shouldn't be used. What i am proposing is that, why do we need to explicitly tell each member that they must speak a certain way.
> If we are not inclusive to begin with, would those who feel marginalized, ever become invested enough in the idea of the community to speak up and raise their demands in the first place?
They will be invested when their preferred pronouns are asked explicitly and used. Also, just to give you an example, when people do something morally good, say planting a tree or segregating waste in the correct bins. They get on a moral high round. So, they think by committing this good act, they can commit a wrong acts on moral grounds. To draw the parallel, people by using certain set of pronouns get on a moral high ground and the segregated community becomes more prone to harassment.
> Could you give an example of a sentence or a snippet of a conversation illustrating the difference caused by the clause you are objecting upon?
When there is a discussion on gender and identity.

**Comment by progmatic-99** [comment] 2020-05-04 13:32
> I believe no one can force me or anyone to do anything, or utter a specific set of words in any community. There are moderators to moderate any discussions if someone feels offended. Then again I'd like to believe I (or anyone who's not a pathological person) will understand and do the right thing to fix the issue at hand. blush

Exactly, i am with you on this that any person in their right sense of mind will know how to behave.
Then, why we need to explicitly define in CoC, the use of a certain set of pronouns. People can approach the moderators if they feel offended.

**Comment by grlwholifts** [comment] 2020-05-04 13:38
Well, for that matter @progmatic-99 this conversation is more of social and moral background, for some "philosophical and learning" discussions, rather than a measure that must be taken.

Nevertheless, it is a good practice that we can follow, as I suggested above, until some other ideologies come up, or maybe, a renewed explanation of our constitution and it's rights! :D You can be the ignition of change, i humbly believe.

Also, about your concern of "certain set of pronouns", I have already mentioned that this shall be taken up in the upcoming volunteer meeting. I suppose you can suggest a wholesome guide of pronouns that would be agreeable by all. In this way diversity as well as inclusiveness of all people will be promoted in the community. And yes, if someone does feel offended, they can definitely approach the moderators, since we all want to work towards the betterment of this community!

**Comment by progmatic-99** [comment] 2020-05-04 13:45
Also, i would like to draw your attention to a certain message regarding this issue in ILUG-D telegram group by ```sonicscrewdriver```. **The message is deleted now.**
```What this person said in their message is that, i am a privileged person and that is why i am concerned about my free speech and i do not know what the LGBTQ+ community goes through in this country.```
Now, how this person can say that i come from a privileged background when ```they don't know me personally.``` Maybe, i am not that privileged. How can they assume that i come from a privileged background?```
So, the argument this person puts forward is that **just because i don't belong to a certain community, i can't put forward my views. This is the kind of identity politics, i am strictly against. If i gave my views, in written, to a person belonging to the LGBTQ+ community and they said them, would that make my views more legible. Now, i think everyone agrees that we should be open to everyone's POV then why when someones puts a view different from theirs ```sonicscrewdriver``` says that you are a privileged person and you don't know what LGBTQ+ community goes through in this country***

I think  we should ```Practice what we preach```.

**Comment by progmatic-99** [comment] 2020-05-04 13:51
> > If you are not sure about a members preferred pronouns or they are not explicit about it, the best way is to use Gender Neutral pronouns (they/them) or politely ask them - **"Hey, what's your preferred pronouns**" before addressing them. This is way safer than hurting sentiments using wrong pronouns.
> 
> Continuing on comments by @iayanpahwa, I would like to propose some changes to the existing CoC :
> 
>     * It is suggested for all participants to add the choice of their pronoun in their `username`/`bio` hence allowing them freedom to choose their self-identity.
> 
>     * For new joinees/inactive participants/any other reason, they can be referred to as `they`
> 
>     * For hints at the choice of pronouns, please have a look [here](https://uwm.edu/lgbtrc/support/gender-pronouns/):
> 
> 
> ![photo_2020-05-04 14 54 49](https://user-images.githubusercontent.com/30324532/80952457-52a29480-8e17-11ea-92b8-0284f01fced9.jpeg)
> 
> Do note that all these practices have been taken up from open source communities/promoters like Fedora/Outreachy etc which have pretty strict community abidance rules. IMHO, this argument now satisfies all the concerns and hence be closed.
> This issue will however, be addressed in the volunteer meeting for better implementation and discussion.

I think this is a much better solution than explicitly writing in the CoC, members should use Gender neutral pronouns. But i think, we can also improve this solution.

**Comment by progmatic-99** [comment] 2020-05-04 13:56
> Well, for that matter @progmatic-99 this conversation is more of social and moral background, for some "philosophical and learning" discussions, rather than a measure that must be taken.
**I think that every community is a social place and morality shouldn't be comprised anywhere. So, it's a measure that can be taken.** 
> Nevertheless, it is a good practice that we can follow, as I suggested above, until some other ideologies come up, or maybe, a renewed explanation of our constitution and it's rights! :D You can be the ignition of change, i humbly believe.
> 
> Also, about your concern of "certain set of pronouns", I have already mentioned that this shall be taken up in the upcoming volunteer meeting. I suppose you can suggest a wholesome guide of pronouns that would be agreeable by all. In this way diversity as well as inclusiveness of all people will be promoted in the community. And yes, if someone does feel offended, they can definitely approach the moderators, since we all want to work towards the betterment of this community!

**Comment by iayanpahwa** [comment] 2020-05-04 15:42
@progmatic-99 

> But, by telling members to use Gender Specific Pronouns, you are telling them what they must speak, thus, in a way you are curtailing their free speech. Instead of telling what we can't say, you are telling the members what we must say.

 *Gender Neutral not Gender Specific* and I hope we both can agree on addressing an individual with a pronoun they don't associate their identity with is morally wrong and it's not hampering your freedom of speech. 

>  Also, any person in their right sense of mind will understand their surroundings and act accordingly.

I wish that's the case my friend. This CoC is specially adopted for this specific community based on past incidents and it has been observed in the past that even right people in right sense are guilty of this, hence community felt need of adding this in place. Now I am not saying the acts were intentional but even innocent mistakes can cause big distress so rather than committing a mistake and asking for forgiveness the CoC asks individual to take a step back and act so the chances of the mistake is minimal and everyone's interest is preserved . 


> I agree with you that we can ask an individual their preferred pronoun, then why do we need it as an explicit rule in CoC.

Because this doesn't comes natural to everyone. Even I am guilty of this in the past many times until I was educated by the right people . Now this whole scenario can be different for different people including it's impact on an individual but taken the interest of wider audience the CoC believes asking before acting is more safer approach. 


> What this signifies is a form of far-left ideology. Though your intentions are of goodwill but the consequences might not be the same.

A model is as good as the results and so far it is working better for the community than before

> Also most of these pronouns are made by radical left ideologues. So, not using these pronouns is not grammatically incorrect. Whereas, on an ethical moral ground, it may differ from person to person.

I would like conversation not to go in that direction to keep it limited to interest of this particular community. 


> Also, socially, how can you, based on your prejudices, decide for a larger group of people, what is socially acceptable or not?

A CoC is deciding entity of what is socially acceptable for this group


>Thanks for your viewpoints!!
At last, we both want the same thing but the path is different.

Which is totally normal thing and having this discussion is healthy, this will be put forward in next volunteer call and based on everyone's feedback we will take this forward. If there is a huge gap in standpoint of the volunteer we may have an internal vote to decide If the current CoC needs changes or not, so the future of this issue can go two paths:

### It will be closed without any change to CoC if majority agrees it's healthy to stay as like
### A PR will be requested with suitable changes, review and merged to address and finally close this issue. 

Thanks
------------------------------------------------------------------------

**Comment by Sc0rpi0n101** [comment] 2020-05-04 15:47
I think the points under **Examples of behaviour that contribute to create a positive environment** including _pt6._ `"Using and promotion use of gender neutral pronouns"`(although it feels grammatically suspicious) are more of behavioral suggestions for a well, positive environment in the community instead of hard set rules that bar you from doing otherwise. It's not like someone's ever stopped you, or someone else for that matter from using he/she/any other gender-specific pronoun.

I can think of two types of scenarios where these pronouns are used:

1) While interacting with someone new/someone you don't know beforehand, you might assume their gender and use a pronoun specific to that gender. If your assumption is right, well, there's no problem. Even if your assumption is wrong and the individual prefers any other pronoun, it's not a problem IMO, you can just continue to use the pronoun they prefer from that point on. But, and that's why I personally advocate the use of gender-neutral pronouns, it's just better to leave some assumptions out of some places/situations. 

2) While addressing the general audience in case of promotions, to provide any information to the community, etc. In such cases, if you use a gender-specific pronoun, like the most used example, `hey guys`, you are only addressing a subset of the community and leaving out everyone that doesn't identify with that pronoun. Unless you want to do that explicitly for some specific situation, using gender-neutral pronouns is advised as it includes everyone in the community irrespective of their gender. 

If anyone has any other scenario where it matters, you're welcome to include it. 


> By making this a rule in the community, what you are doing is imposing a restriction on a person's individuality and their liberty because a group of people in a community are telling the rest of the group, what words they should be using. 

> The problem arises when in a community, it is imposed by other people on a large group of people.

These "other people" you're referencing, as @iayanpahwa said, are the community volunteers moderators and they represent the views and enforce the guidelines of the community, not their own opinions. These other people's actions represent the community's choices. For example, if this discussion results in any change in the community's CoC and guidelines, these people will be enforcing the new standard, and again, not their own opinions.

Now for your other point,,
> But, we also have to look into the fact that by telling anyone in a community that you have to use gender-neutral pronouns, you are taking away the individual's Right to freedom of Expression and Speech.

> Again, what i am against is the community at large telling an individual that they must speak a certain way.

I only have one questions, and I'm including the definition of Right to freedom of Expression defined under Article 19 of the Universal Declaration for Human Rights for reference:
```
Everyone has the right to freedom of opinion and expression; this right includes freedom to hold 
opinions without interference and to seek, receive and impart information and ideas through any 
media and regardless of frontiers.
```

So, by your logic, if the community telling an individual to speak a certain way is a curb on that individual's Right to Freedom of Expression, then the following points covered in the **Examples of unacceptable behaviour by participants** section of the CoC referenced herein

- Use of sexualised language or imagery and unwelcome sexual attention or advances
- Use of sexist or racist comments, discrimination or encouragement of exclusions
- Public or private harassment i.e. trolling, insulting/derogatory comments, mocking, abrupt language and personal/political attack in events and official forums
- Publishing others' private information, such as a physical or electronic address, without explicit permission
- Other conduct which could reasonably be considered inappropriate in a professional setting

are also a curb to an individual's right to freely express his opinions. 

So, my question is, If you believe telling an individual to not behave a certain way is a curb to the freedom of expression and you're willing to contest the removal/updation of the Gender-neutral pronoun rule, Are you also willing to contest that telling an individual not to behave unprofessionally,  or not use discriminatory language or not to harras other people, etc. is also a curb to that individual's Right to freedom of expression?

**Comment by iayanpahwa** [comment] 2020-05-04 15:52
@Sc0rpi0n101 very well said, thank you for your insights and inputs

**Comment by bhanuvrat** [comment] 2020-05-05 12:24
PS: you quoted your replies too :( 

> > Hi @progmatic-99 Two questions.
> > Do we, as a community, want create an environment where present and future members want to engage?
> Yes, i agree with you that we, as a community, should be inclusive to all. But, i am not saying that gender neutral pronouns shouldn't be used. What i am proposing is that, why do we need to explicitly tell each member that they must speak a certain way.

I'm glad we agree on this.

> > If we are not inclusive to begin with, would those who feel marginalized, ever become invested enough in the idea of the community to speak up and raise their demands in the first place?
> They will be invested when their preferred pronouns are asked explicitly and used.

Okay. Gender neutral pronouns also apply to statements made in general, where there is no specific person who can be taken into account. Haven't you had an opportunity to look at textbooks where first there were statements like:

"The user made a mistake. *He* clicked on submit before filling the form".

Then they overcompensated with:

"The user made a mistake. *She* submitted the form without filling it"

The CoC in its present form would request you use "they" instead of gender specific pronoun. This is a subtle example of a much larger issue highlighted in @Sc0rpi0n101 's comments.

> Also, just to give you an example, when people do something morally good, say planting a tree or segregating waste in the correct bins. They get on a moral high round. So, they think by committing this good act, they can commit a wrong acts on moral grounds. To draw the parallel, people by using certain set of pronouns get on a moral high ground and the segregated community becomes more prone to harassment.

I agree that we need to keep pride in check. I believe that when a member of the community becomes aware of their skills, potential, knowledge and those of the rest of the members they realize what the community has to offer and then *ghamand* automatically vanes off. 

> > Could you give an example of a sentence or a snippet of a conversation illustrating the difference caused by the clause you are objecting upon?
> When there is a discussion on gender and identity.

This does not answer my question.

PS: @Sc0rpi0n101 has summarized the points better than I would.

**Comment by progmatic-99** [comment] 2020-05-05 13:41
@iayanpahwa That's the way to go forward. The decision made by the community members will be last.
I just provided a different perspective. Thanks for listening to my POV.

**Comment by progmatic-99** [comment] 2020-05-05 13:53
@Sc0rpi0n101 
**Read all the comments that i have put here and above.**
Please read what i am proposing. I am against one thing, that does not mean I am promoting others.
As the right you defined, there are also restriction that come together with the right to freedom and expression.
**Clause (2) of Article 19 contains the grounds on which restrictions on the freedom of speech and expression can be imposed-

1) Security of State: Under Article 19(2) reasonable restrictions can be imposed on freedom of speech and expression in the interest of security of State. The term “security of state” refers only to serious and aggravated forms of public order e.g. rebellion, waging war against the State, insurrection and not ordinary breaches of public order and public safety, e.g. unlawful assembly, riot, affray. Thus speeches or expression on the part of an individual, which incite to or encourage the commission of violent crimes, such as, murder are matters, which would undermine the security of State.

2) Friendly relations with foreign states: This ground was added by the constitution (First Amendment) Act, 1951. The object behind the provision is to prohibit unrestrained malicious propaganda against a foreign friendly state, which may jeopardise the maintainance of good relations between India, and that state. No similar provision is present in any other Constitution of the world. In India, the Foreign Relations Act, (XII of 1932) provides punishment for libel by Indian citizens against foreign dignitaries. Interest of friendly relations with foreign States, would not justify the suppression of fair criticism of foreign policy of the Government.

It is to be noted that member of the commonwealth including Pakistan is not a “foreign state” for the purposes of this Constitution. The result is that freedom of speech and expression cannot be restricted on the ground that the matter is adverse to Pakistan.

3) Public Order: This ground was added by the Constitution (First Amendment) Act. ‘Public order’ is an expression of wide connotation and signifies “that state of tranquility which prevails among the members of political society as a result of internal regulations enforced by the Government which they have established.”

Public order is something more than ordinary maintenance of law and order. ‘Public order’ is synonymous with public peace, safety and tranquility. The test for determining whether an act affects law and order or public order is to see whether the act leads to the disturbances of the current of life of the community so as to amount to a disturbance of the public order or whether it affects merely an individual being the tranquility of the society undisturbed.

Anything that disturbs public tranquility or public peace disturbs public order. Thus communal disturbances and strikes promoted with the sole object of acausing unrest among workmen are offences against public order. Public order thus implies absence of violence and an orderly state of affairs in which citizens can peacefully pursue their normal avocation of life. Public order also includes public safety. Thus creating internal disorder or rebellion would affect public order and public safety. But mere criticism of government does not necessarily disturb public order. In its external aspect ‘public safety’ means protection of the country from foreign aggression. Under public order the State would be entitled to prevent propaganda for a state of war with India.

The words ‘in the interest of public order’ includes not only such utterances as are directly intended to lead to disorder but also those that have the tendency to lead to disorder. Thus a law punishing utterances made with the deliberate intention to hurt the religious feelings of any class of persons is valid because it imposes a restriction on the right of free speech in the interest of public order since such speech or writing has the tendency to create public disorder even if in some case those activities may not actually lead to a breach of peace. But there must be reasonable and proper nexus or relationship between the restrictions and the achievements of public order.

4) Decency or morality: The words ‘morality or decency’ are words of wide meaning. Sections 292 to 294 of the Indian Penal Code provide instances of restrictions on the freedom of speech and expression in the interest of decency or morality. These sections prohibit the sale or distribution or exhibition of obscene words, etc. in public places. No fix standard is laid down till now as to what is moral and indecent. The standard of morality varies from time to time and from place to place.

5) Contempt of Court: Restriction on the freedom of speech and expression can be imposed if it exceeds the reasonable and fair limit and amounts to contempt of court. According to the Section 2 ‘Contempt of court’ may be either ‘civil contempt’ or ‘criminal contempt.’

6) Defamation: A statement, which injures a man’s reputation, amounts to defamation. Defamation consists in exposing a man to hatred, ridicule, or contempt. The civil law in relating to defamation is still uncodified in India and subject to certain exceptions.

7) Incitement to an offence: This ground was also added by the constitution (First Amendment) Act, 1951. Obviously, freedom of speech and expression cannot confer a right to incite people to commit offence. The word ‘offence’ is defined as any act or omission made punishable by law for the time being in force.

8) Sedition: As understood by English law, sedition embraces all those practices whether by words, or writing which are calculated to disturb the tranquility of the State and lead ignorant person to subvert the government. It should be noted that the sedition is not mentioned in clause (2) of Art. 19 as one of the grounds on which restrictions on freedom of speech and expression may be imposed.**
So, I don't think that the things you mentioned besides the use of ```Gender Neutral Pronouns, when explicitly told by a community```, curb my freedom  of speech. Even if i thought so or practised so, i can be legally prosecuted for that.

**Read all the comments that i have put.**

**Comment by progmatic-99** [comment] 2020-05-05 14:04
@bhanuvrat 
The last decision lies with the community members. I am ready to accept it.

> I agree that we need to keep pride in check. I believe that when a member of the community becomes aware of their skills, potential, knowledge and those of the rest of the members they realize what the community has to offer and then ghamand automatically vanes off.

Also, what are you trying to put forward?
The point that i was trying to make above was something different.

**Comment by SonicScrewdriver** [comment] 2020-05-05 15:05
Ummm I'm sorry, what is going on? I haven't commented in the telegram group at all. I have no idea what this is, and I'm not in the India group. I'm not a member of this community, and I have no interest in hindering any discussion -- in fact I love a good healthy & respectful debate. I have not made any posts anywhere regarding any of this content, as it's a topic I tend to stick out of. I'm actually in Canada myself and, while I'm an ally, I'm not exactly a member of the LGBTQ+ community. 

Seriously, I think you've tagged the wrong person. I wish you all the best, but I really don't know what's going on here.

**Comment by iayanpahwa** [comment] 2020-05-05 16:04
@SonicScrewdriver yes you’ve been wrongly tagged by @progmatic-99 , I believe it is a username confusion. Please feel free to unsubscribe for this conversation, and sorry for the buzz :)

**Comment by progmatic-99** [comment] 2020-05-05 16:22
@SonicScrewdriver 
This is a mistake on my part. I wanted to tag a different person with the same username.
Apologies for the disturbance.

**Comment by iayanpahwa** [comment] 2020-05-05 17:00
Everyone ,

this has been discussed in today's community call 

```
The current CoC clause "Using and promotion use of gender neutral pronouns" *encourages* members to use neutral pronouns.
No one in the past has been blocked but rather educated in right way when not using the neutral pronouns, so in the interest of community,
we don't see a need to remove this clause from the CoC as of now, though we definitely can encourage the members to put their preffered pronouns
in their TG bio, so anyone addressing them can refer that before hand, but when addressing a wider audience / entire group we still recommend using gender
neutral pronouns, refer- https://heyguys.cc to know more ...
```

Closing the issue based on above comments.

**Closed as completed by iayanpahwa** 2020-05-05 17:00 UTC
